### ISSUE TITLE
syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

### ISSUE THREAD

**Issue by mengtaixiao** [ponycool/typecho-plugins#2]
点激活提示这个,不熟悉php,是不是哪里语法括号没填好

syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

**Comment by mengtaixiao** [comment]
追悼模式插件的php的问题

**Comment by ponycool** [comment]
> 点激活提示这个,不熟悉php,是不是哪里语法括号没填好
> 
> syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

确定下是否是最新代码，另外你的环境是否是PHP8以上？

**Comment by ponycool** [comment]
> 点激活提示这个,不熟悉php,是不是哪里语法括号没填好
> 
> syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

提供的信息有限，尽可能的提供下更多信息

**Comment by losie** [comment]
syntax error, unexpected '=>' (T_DOUBLE_ARROW)
是不是插件不适合8.0以下

**Comment by ponycool** [comment]
> syntax error, unexpected '=>' (T_DOUBLE_ARROW) 是不是插件不适合8.0以下

之前有收到这个反馈，确实是使用了PHP8的某些语法，在PHP8.0以下会报错

**Comment by ponycool** [comment]
> syntax error, unexpected '=>' (T_DOUBLE_ARROW) 是不是插件不适合8.0以下

**Comment by ponycool** [comment]
> 点激活提示这个,不熟悉php,是不是哪里语法括号没填好
> 
> syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

看下运行环境是否是PHP8.0以上
